#pragma once
#include <WiFiClientSecure.h>

// TLS trust for every outbound request.
//
// The clients used to call setInsecure(), which encrypts but never checks who
// it is talking to — anything able to intercept the connection could have fed
// the board whatever departures it liked. They now verify against Mozilla's
// root store, the same set a browser trusts.
//
// The bundle is generated by docs/gen_crt_bundle.py into
// data/cert/x509_crt_bundle.bin and embedded by platformio.ini's
// `board_build.embed_files`. Only subjects and public keys are stored, so 121
// roots cost about 55KB of flash and almost no RAM — esp_crt_bundle.c keeps
// just an index and binary-searches it.
extern const uint8_t rootca_crt_bundle_start[] asm("_binary_data_cert_x509_crt_bundle_bin_start");

namespace net {

// Point a client at the embedded root store. Call before begin().
//
// Building with -DTLS_INSECURE falls back to the old unverified behaviour. That
// exists to diagnose a server whose chain is genuinely missing from the bundle
// — a certificate failure is otherwise indistinguishable from the network being
// down — and is never how a release should be built.
inline void trustRoots(WiFiClientSecure& client) {
#ifdef TLS_INSECURE
    client.setInsecure();
#else
    client.setCACertBundle(rootca_crt_bundle_start);
#endif
}

}  // namespace net
